services:
  nginx:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    image: nginx:1.24.0
    container_name: dnmp_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./sites:/var/www/html
    depends_on:
      - php81
      - php83

  php81:
    build:
      context: .
      dockerfile: /php/8.1/Dockerfile
    container_name: dnmp_php81
    volumes:
      - ./php/extensions:/var/www/html/extensions
      - ./sites:/var/www/html

  php83:
    build:
      context: .
      dockerfile: /php/8.3/Dockerfile
    container_name: dnmp_php83
    volumes:
      - ./php/extensions:/var/www/html/extensions
      - ./sites:/var/www/html

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: dnmp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
      

  redis:
    image: redis:alpine
    container_name: dnmp_redis
    volumes:
     - ./redis/data:/data
    