CREATE DATABASE IF NOT EXISTS `test` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'root';

GRANT ALL PRIVILEGES ON `test`.* TO 'root'@'%';

FLUSH PRIVILEGES;
